### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by saipat** [saipat/Eton#1]
# Wiki Page Home
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page
## Comments
---
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
Includes the following list for the 4 app specific MVPs:
    - [x] Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments
---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique ( 1) You added a unique constraint on the name of a notebook. That means a name of "cat names" can only show up once on the table. Is that you wanted? 2) There are some other opportunities to add uniqueness to your tables :) do you see them? ) 
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
* Do you mean `sessiontoken` or `session_token`? 
---
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
---
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments

* `/api/notes/tags/:tag_id` can be changed to `/api/tags/:tag_id`!
* same as above for `GET /api/notes/notebooks/:notebook_id`
* how does a user create a new tag?
---
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by xnanodax** [comment]
Great start on the proposal :) You have put in a lot of thought! We have some changes to do. I will check for updates on your proposal some time tomorrow! Thanks Sai!

Friendly Reminders:
* This is the only github issue where I will be marking the check boxes :) All the other github issues, you'll be checking off boxes!
* Please reach out here (this Github issue) if you have any further questions!

**Comment by saipat** [comment]
Hi Cynthia, 

the reason I don't have a create tag is because the user cannot create a tg without creating /editing a note. So, My idea is that whenever a user creates/edits a note, i will check for the tagId. if there is one, I will the tag value  add it to the tags_notes join table, else, i will add null.

I have a doubt on this one "/api/notes/tags/:tag_id can be changed to /api/tags/:tag_id"  - Since I am not writing a route for the create tag, if I want to access all the notes for a specific tag, I need notes in my routes like /api/notes/tags/:tag_id right? and the same idea for the notebooks too.

For the Backend Routes, I don't have GET likes api endpoint in my routes.

And I will read about React Quill. I wanted to show the preview of the user notes and let the user search by their preference(either in rich text or by plain text). I will do my research on that. 

Finally, shall I start my project with what I have now?

**Comment by xnanodax** [comment]
Done :)! 💯
